spring:
  application:
    name: mmrTest

  # 1. H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL # 메모리 모드 (PostgreSQL 문법 호환)
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # 2. JPA 및 Hibernate 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티 구조에 맞춰 테이블 자동 생성/수정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 3. H2 콘솔 설정 (웹 브라우저에서 DB 접속 허용)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
riot:
  api:
    key: "RGAPI-953aad66-fad4-46af-8e1e-48856577290c"

